### ISSUE TITLE
Loading screen in 2.4.0

### ISSUE THREAD

**Issue by vsy2876** [AZoneLive/PersonalZone#1]
When I click on a particular title it just loads and nothing happens further.
This is for the 2.4.0 universal apk. Hope this gets a fix. Thanks for your contribution.

**Comment by AZoneLive** [comment]
Hi, would you mind sharing your phone's architecture (or model name) and the title's name?

**Comment by AZoneLive** [comment]
> When I click on a particular title it just loads and nothing happens further.
> This is for the 2.4.0 universal apk. Hope this gets a fix. Thanks for your contribution.

Hi, would you mind sharing your phone's architecture (or model name) and the title's name?

**Comment by vsy2876** [comment]
> > When I click on a particular title it just loads and nothing happens further.
> > This is for the 2.4.0 universal apk. Hope this gets a fix. Thanks for your contribution.
> 
> Hi, would you mind sharing your phone's architecture (or model name) and the title's name?

OnePlus 8 Pro and any title I click on shows that message unless and I search for it and then open it

**Comment by AZoneLive** [comment]
> > > When I click on a particular title it just loads and nothing happens further.
> > > This is for the 2.4.0 universal apk. Hope this gets a fix. Thanks for your contribution.
> > 
> > 
> > Hi, would you mind sharing your phone's architecture (or model name) and the title's name?
> 
> OnePlus 8 Pro and any title I click on shows that message unless and I search for it and then open it

Seems it happens when selecting a title from the MAL/AniList screen and a similar bug to the one in 2.4.5. I'll try and look into it but cannot guarantee anything can be done. The original AnimeZone app was made in Flutter and reverse engineering it is impossible, and without the source, it's highly unlikely a fix can be implemented. I would recommend just using the search function and then its recent activities page for now.

**Comment by vsy2876** [comment]
I remember using the MAL list screen to select anime from your app so it worked before just not now. 
I appreciate you trying even if it doesn't work.
Keep up the good work!

**Comment by AZoneLive** [comment]
I see, thank you!
