### ISSUE TITLE
Lucy and Erza servers not working in 2.4.0

### ISSUE THREAD

**Issue by vsy2876** [AZoneLive/PersonalZone#2]
Sorry to bother you again but Erza server doesn't show any quality at all to select and Lucy once selected shows an error occurred. 
This is all on the 2.4.0 version of the app.
I hope you fix this like you fixed it in the 2.4.5 version as well.
Also please do include your mail id I would like to email you some information

**Comment by AZoneLive** [comment]
> Sorry to bother you again but Erza server doesn't show any quality at all to select and Lucy once selected shows an error occurred.
> This is all on the 2.4.0 version of the app.
> I hope you fix this like you fixed it in the 2.4.5 version as well.

Hi, sorry, this won't be possible. Version 2.4.5 was made by the original developer to hotfix those servers and a few other bugs. I don't have any control over the servers in any of the versions as that'd require I have (or decompile) the original source, which isn't possible with Flutter applications. I can only really keep the app online and able to open without the loading screen crash and using a new, working simkl key. Anything else is most likely out of my control. The servers may eventually all die out and once that happens, I'm afraid I won't be able to do anything about it and AnimeZone will truly be dead. But for now, I'm just trying to keep this amazing app going for as long as possible, even if it's on its last legs.

**Comment by vsy2876** [comment]
> > Sorry to bother you again but Erza server doesn't show any quality at all to select and Lucy once selected shows an error occurred.
> > This is all on the 2.4.0 version of the app.
> > I hope you fix this like you fixed it in the 2.4.5 version as well.
> 
> Hi, sorry, this won't be possible. Version 2.4.5 was made by the original developer to hotfix those servers and a few other bugs. I don't have any control over the servers in any of the versions as that'd require I have (or decompile) the original source, which isn't possible with Flutter applications. I can only really keep the app online and able to open without the loading screen crash and using a new, working simkl key. Anything else is most likely out of my control. The servers may eventually all die out and once that happens, I'm afraid I won't be able to do anything about it and AnimeZone will truly be dead. But for now, I'm just trying to keep this amazing app going for as long as possible, even if it's on its last legs.

I see thank you so much for the information and keeping this app alive. Also do post any information or reddit at r/animeapp as I keep posting updates about the app.
