### ISSUE TITLE
No server working....is the app dead?

### ISSUE THREAD

**Issue by vsy2876** [AZoneLive/PersonalZone#3]
No version of the app can be used as the infinite loading occurs on every server. Is the app dead or can there be any tweak to it?

**Comment by AZoneLive** [comment]
Sorry, I'm unsure as to what is happening with the app. It seems the simkl side of it is malfunctioning but I can't find any clear reasons as to why. It may be a temporary problem with simkl or permanent. We'll just have to wait and see.

**Comment by AZoneLive** [comment]
Back online and working. Open another issue if the problem arises again.
