### ISSUE TITLE
Batch downloader not working

### ISSUE THREAD

**Issue by Froggy-Boi** [AZoneLive/PersonalZone#5]
Manu links appear when wanting to stream an episode but they don't show up on the download. I've already tried both .ai .sh

**Comment by AZoneLive** [comment]
> Manu links appear when wanting to stream an episode but they don't show up on the download. I've already tried both .ai .sh

Reproducible issue, but I don't believe it will be fixable as I don't have the original application's source code. However, the downloaded episodes (if download _was_ completed,) can be found in your Phone's Main Storage -> AnimeZone -> Download.
