### ISSUE TITLE
app completely stopped working for me

### ISSUE THREAD

**Issue by Zeynex** [AZoneLive/PersonalZone#6]
Heya the app didnt load anime pages for days for me now so today i reinstalled it and now the search seems to not even work anymore ... logging into mal was also infinitly but it seems to still have done it after an app restart

**Comment by reiny2000** [comment]
Same here. Tried it with both this and a version of the original that I modified the GitHub link and key when AZ shut down and both of them don't work. It might be game over.

**Comment by vsy2876** [comment]
RIP

**Comment by StockiChan** [comment]
We all know we need this App so we have to fight for it

**Comment by StockiChan** [comment]
I solved the problem you have to press the gogoanime.ai and then restart it then it works fine 

Thank me later and have a good day with anime or Hentai

**Comment by Zeynex** [comment]
> I solved the problem you have to press the gogoanime.ai and then restart it then it works fine
> 
> Thank me later and have a good day with anime or Hentai

It really does lol ... So back when he got dcmaed it didnt work anymore and now it does again? His is ironic ^^'

**Comment by AZoneLive** [comment]
> I solved the problem you have to press the gogoanime.ai and then restart it then it works fine
> 
> Thank me later and have a good day with anime or Hentai

Been away for the past few days so didn't have time to answer this question, but thanks for noting of the solution. Closing issue now.
